export const data = [
    {
        "id": "1",
        "name": "Sawsan Kamal Haj",
        "room": "",
        "activity": "Follow-up",
        "reason": "Poliomyelitis",
        "seen": "",
        "new": "No",
        "referral": "",
        "location": "Jounieh Clinic",
        "address": "Jounieh, Talal street C021",
        "site": "clinic",
        "type": "visit",
        "arrived": "",
        "dateTime": "2015-05-08T08:00:19"
    },
    {
        "id": "2",
        "name": "Toni Hamdan",
        "room": "",
        "activity": "New Condition",
        "reason": "Ewing's sarcoma",
        "seen": "",
        "new": "Yes",
        "referral": "",
        "location": "Jounieh Clinic",
        "address": "Jounieh, Talal street C021",
        "site": "clinic",
        "type": "visit",
        "arrived": "",
        "dateTime": "2015-05-08T08:15:19"
    },
    {
        "id": "3",
        "name": "Zaher Halabi",
        "room": "",
        "activity": "Follow-Up",
        "reason": "Cerebral palsy",
        "seen": "",
        "new": "No",
        "referral": "",
        "location": "Jounieh Clinic",
        "address": "Jounieh, Talal street C021",
        "site": "clinic",
        "type": "visit",
        "arrived": "",
        "dateTime": "2015-05-08T08:40:19"
    },
    {
        "id": "4",
        "name": "John Smith",
        "room": "4 floor / 485",
        "activity": "New Condition",
        "reason": "Kyphosis",
        "seen": "Yes",
        "new": "",
        "referral": "",
        "location": "Al-zahraa Hospital",
        "address": "Beirut, Jnah",
        "site": "hospital",
        "type": "floor",
        "status": "",
        "arrived": "",
        "dateTime": "2015-05-08T10:00:19"
    },
    {
        "id": "5",
        "name": "John Smith",
        "room": "4 floor / 485",
        "activity": "New Condition",
        "reason": "Kyphosis",
        "seen": "Yes",
        "new": "",
        "referral": "",
        "location": "Al-zahraa Hospital",
        "address": "Beirut, Jnah",
        "site": "hospital",
        "type": "floor",
        "status": "",
        "arrived": "",
        "dateTime": "2015-05-08T10:05:19"
    },
    {
        "id": "6",
        "name": "Piano",
        "room": "2 floor / 215",
        "activity": "Follow-up",
        "reason": "Low Back Pain",
        "seen": "Yes",
        "new": "",
        "referral": "",
        "location": "Al-zahraa Hospital",
        "address": "Beirut, Jnah",
        "site": "hospital",
        "type": "visit",
        "arrived": "",
        "dateTime": "2015-05-08T10:30:19"
    },
    {
        "id": "7",
        "name": "Sami",
        "room": "3 floor / 302",
        "activity": "Follow-up",
        "reason": "Torn Meniscus",
        "seen": "No",
        "new": "",
        "referral": "",
        "location": "Al-zahraa Hospital",
        "address": "Beirut, Jnah",
        "site": "hospital",
        "type": "floor",
        "arrived": "",
        "dateTime": "2015-05-08T11:00:19"
    },
    {
        "id": "8",
        "name": "Sami",
        "room": "-1 floor / 701",
        "activity": "Operation",
        "reason": "Rheumatoid Arthritis",
        "seen": "",
        "new": "",
        "referral": "",
        "location": "Al-zahraa Hospital",
        "address": "Beirut, Jnah",
        "site": "hospital",
        "type": "operation",
        "arrived": "",
        "dateTime": "2015-05-08T12:30:19"
    },



    {
        "name": "Hamza Al-Harake",
        "room": "Room 1",
        "activity": "Follow-up",
        "reason": "Osteoporosis",
        "seen": "",
        "new": "No",
        "referral": "Dr. Sami",
        "location": "Hamra Clinic",
        "address": "Beirut, Hamra street B023",
        "site": "clinic",
        "type": "visit",
        "arrived": "2015-05-08T14:25:19",
        "dateTime": "2015-05-08T14:30:19"
    },
    {
        "name": "Raji Ali",
        "room": "Room 1",
        "activity": "New Condition",
        "reason": "Hip Fracture",
        "seen": "",
        "new": "No",
        "referral": "",
        "location": "Hamra Clinic",
        "address": "Beirut, Hamra street B023",
        "site": "clinic",
        "type": "visit",
        "arrived": "2015-05-08T14:50:19",
        "dateTime": "2015-05-08T15:00:19"
    },
    {
        "name": "Hamza Al-Harake",
        "room": "",
        "activity": "Follow-up",
        "reason": "Hand Pain and Problems",
        "seen": "",
        "new": "No",
        "referral": "Dr. Sami",
        "location": "Hamra Clinic",
        "address": "Beirut, Hamra street B023",
        "site": "clinic",
        "type": "visit",
        "arrived": "delayed",
        "dateTime": "2015-05-08T15:20:19"
    },
    {
        "name": "Sawsan Hamdar",
        "room": "",
        "activity": "Follow-up",
        "reason": "Ankle Sprain",
        "seen": "",
        "new": "No",
        "referral": "Family",
        "location": "Hamra Clinic",
        "address": "Beirut, Hamra street B023",
        "site": "clinic",
        "type": "visit",
        "arrived": "canceled",
        "dateTime": "2015-05-08T15:35:19"
    },
    {
        "name": "Samah al-ali",
        "room": "",
        "activity": "operation",
        "reason": "Bone fracture repair",
        "seen": "",
        "new": "No",
        "referral": "",
        "location": "Hamra Clinic",
        "address": "Beirut, Hamra street B023",
        "site": "clinic",
        "type": "operation",
        "arrived": "canceled",
        "dateTime": "2015-05-08T15:55:19"
    },
    {
        "name": "Pier hashash",
        "room": "",
        "activity": "New Condition",
        "reason": "Osteochondroma",
        "seen": "",
        "new": "No",
        "referral": "",
        "location": "Hamra Clinic",
        "address": "Beirut, Hamra street B023",
        "site": "clinic",
        "type": "visit",
        "arrived": "",
        "dateTime": "2015-05-08T16:15:19"
    },
    {
        "name": "Diana",
        "room": "",
        "activity": "Follow-up",
        "reason": "Poliomyelitis",
        "seen": "",
        "new": "No",
        "referral": "",
        "location": "Hamra Clinic",
        "address": "Beirut, Hamra street B023",
        "site": "clinic",
        "type": "visit",
        "arrived": "",
        "dateTime": "2015-05-08T16:40:19"
    }


]